# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a62656208c561028d2c0ca583592f815"
name = "synergistic-strategy-app"
handle = "synergistic-strategy-app-12"
application_url = "http://remixs-shopify-mongo-demo.vercel.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
  
[auth]
redirect_urls = ["http://remixs-shopify-mongo-demo.vercel.app/auth/callback", "http://remixs-shopify-mongo-demo.vercel.app/auth/shopify/callback", "http://remixs-shopify-mongo-demo.vercel.app/api/auth/callback"]

[pos]
embedded = false
