# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aec4af87de80e641deade3f17ef9d052"
name = "dba80-app"
handle = "dba80-app-12"
application_url = "https://debt-soonest-region-nr.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07" 

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"
  
[auth]
redirect_urls = ["https://debt-soonest-region-nr.trycloudflare.com/auth/callback", "https://debt-soonest-region-nr.trycloudflare.com/auth/shopify/callback", "https://debt-soonest-region-nr.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
